### ISSUE TITLE
'DataFrame' object has no attribute 'objectid'

### ISSUE THREAD

**Issue by r7butler** [SCCWRP/changerequest#2]
@duynguyen2019  do you think you can put a comment here describing this issue? Since you are the one that figured out the cause of the problem

**Comment by duynguyen2019** [comment]
When the user changes the records that have fields as primary keys, the app recognizes the changes as "records need to be delete" and "records need to be added". To be specific, it will attempt to delete the changed records, and add them again with the new values, and the records will also have new objectid.

The bug occurred when the user hits "Save current Changes" button if there are no modified records, meaning the user might change the records that have fields as primary keys (or they actually add/delete new records). I don't know where exactly in the code, but I think it's trying to call an objectid column on an empty dataframe.

I'll look into this issue when I get a chance.

**Comment by r7butler** [comment]
> 

Definitely, if/when you work on it, just be sure to make a branch for this issue

I've been working on this thing mostly alone and have just done all development on a single branch

**Comment by duynguyen2019** [comment]
I've fixed this issue by checking the length the HTML collections in the <tbody> for the modified records div-container.

If there are no changed records, meaning length = 0, then just pop a Javascript alert telling the user.

The fix: 
![image](https://user-images.githubusercontent.com/55409702/198815003-d6b87b59-be7c-4f36-b634-269165c5539f.png)

Hence, I am closing this issue.
