### ISSUE TITLE
enhancement - warn user if the login info dropped does not match session info

### ISSUE THREAD

**Issue by zaibquraishi** [SCCWRP/changerequest#22]
Issue a warning to the user if the login info from the excel file does not match the session login info. 

This is to prevent the changing data with a different submissionid that the one selected from the login. This would cause issues with tracking info with the change history table if the data changed and selected have different submissionids.

**Comment by r7butler** [comment]
submissionid and the login fields should be immutable, there is a variable in the app config called "immutable fields" (I think) that are fields that do not get affected even if the user edits in the excel file

**Comment by r7butler** [comment]
The login information is not provided in the download given to the user - no system fields are provided to the user except for ObjectID
