### ISSUE TITLE
formatting in return comparison file (modified tab) marks incorrect cells

### ISSUE THREAD

**Issue by zaibquraishi** [SCCWRP/changerequest#5]
use the following login information: 
email: janw@sccwrp.org
agency: SCCWRP
submissionid: 1638554208
table: tbl_edna_metadata

drop file:
[tbl_sedgrainsize_metadata_1638554208.xlsx](https://github.com/SCCWRP/changerequest/files/11237585/tbl_sedgrainsize_metadata_1638554208.xlsx)
[1681485456_comparison.xlsx](https://github.com/SCCWRP/changerequest/files/11237586/1681485456_comparison.xlsx)

return comparison file: 
[1681485456_comparison.xlsx](https://github.com/SCCWRP/changerequest/files/11237589/1681485456_comparison.xlsx)
[tbl_sedgrainsize_metadata_1638554208.xlsx](https://github.com/SCCWRP/changerequest/files/11237590/tbl_sedgrainsize_metadata_1638554208.xlsx)
modified sheet has green formatted cells marked many rows below the actual changed data (latitude, longitude values only)

**Comment by r7butler** [comment]
Issue of grossly missing the changed cells is fixed. Apparently there is a similar issue to this one where now the highlighting is out of order

Closing this one because the bug causing this particular issue is fixed
