### ISSUE TITLE
incorrect cells marked in modified records sheet

### ISSUE THREAD

**Issue by zaibquraishi** [SCCWRP/changerequest#8]
The download receipt/comparison excel file has incorrect cells marked in the 'Modified' sheet. 

To replicate the issue, 
1. use the following field entries: 
![image](https://github.com/SCCWRP/changerequest/assets/51800531/e77dfc7c-2be2-4390-a4c0-e23cfa83d1cb)

2. download the submission file 
3. revise ALL values _percentcovercode_ and _daubenmiremidpoint_ where siteid is 'NC-DRA' (replace -88 with some number (int, float, respectively)) 
4. upload file to change request app
5. click download receipt to retrieve comparison file 
6. compare objectid = 3858 between the 'Original' and 'Modifed' sheets to find an example of the error

Note: The changed records table displays the changed cells correctly. **Only the comparison file does NOT.** Occurred in dev branch.
Left half of row (with objectid)
![image](https://github.com/SCCWRP/changerequest/assets/51800531/4503c152-2111-4410-bff6-141619eafcaf)
 Right half of row (with daubenmiremidpoint and percentcover code highlighted in green, respectively)
![image](https://github.com/SCCWRP/changerequest/assets/51800531/8a2a4f5b-a4fc-4763-9c9a-84beb738102b)

Attachments: 
Original File (step 2): 
[cr-bug-tbl_vegetativecover_data_1664395415-nc-dra-origi-dl.xlsx](https://github.com/SCCWRP/changerequest/files/11850067/cr-bug-tbl_vegetativecover_data_1664395415-nc-dra-origi-dl.xlsx)
Updated file for changes for NC-DRA (step 3): 
[cr-bug-tbl_vegetativecover_data_1664395415-nc-dra-updated.xlsx](https://github.com/SCCWRP/changerequest/files/11850076/cr-bug-tbl_vegetativecover_data_1664395415-nc-dra-updated.xlsx)
Comparison file with error - reference objectid 3858 (step 5-6): 
[cr-bug-1687509731_comparison.xlsx](https://github.com/SCCWRP/changerequest/files/11850058/cr-bug-1687509731_comparison.xlsx)

**Comment by zaibquraishi** [comment]
notice that the cells that are changed correspond to the exact rows of the original tab rather than the the specific objectid. that is, when the rows are reordered by ascending objectid in the modified tab, the green cells mark cells do not reflect the exact cells that have been changed

**Comment by r7butler** [comment]
@zaibquraishi thank you for making this clear, i'll look into it when i get a chance

**Comment by r7butler** [comment]
Commit on June 26, 2023 fixes this (Commit ID fb995ba95cc54e6f2c1482673c3fad3725e70658)
